"""empty message

Revision ID: 859a35e3c4de
Revises: c8488636a6d2
Create Date: 2025-09-09 21:33:22.409370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859a35e3c4de'
down_revision = 'c8488636a6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
